columnSuffix: null
contentColumnType: string
fieldGroup: df122fe4-2195-47e9-8049-a601db27ef96 # Modules
handle: accordion
instructions: null
name: Accordion
searchable: false
settings:
  contentTable: '{{%matrixcontent_accordion}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
