columnSuffix: null
contentColumnType: string
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: alpRestaurants
instructions: null
name: Alpwirtschaften
searchable: false
settings:
  contentTable: '{{%matrixcontent_alprestaurants}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
