columnSuffix: null
contentColumnType: string
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: images
instructions: null
name: Bilder
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:5b7d7792-f622-4289-a94e-f10fbe2ab5a9' # Bilder
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:5b7d7792-f622-4289-a94e-f10fbe2ab5a9' # Bilder
  restrictedLocationSubpath: null
  selectionLabel: 'Bild hinzufügen'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:5b7d7792-f622-4289-a94e-f10fbe2ab5a9' # Bilder
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
