columnSuffix: gkupwurh
contentColumnType: string(255)
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: locationLink
instructions: null
name: 'Standort Link'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
