columnSuffix: yzobnahs
contentColumnType: string(640)
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: metaDescription
instructions: 'Meta Beschreibung'
name: 'Meta Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: false
  columnType: null
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
