columnSuffix: flsffhny
contentColumnType: string(260)
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: metaTitle
instructions: null
name: 'Meta Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 65
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
