columnSuffix: null
contentColumnType: string
fieldGroup: df122fe4-2195-47e9-8049-a601db27ef96 # Modules
handle: modules
instructions: null
name: Inhaltsmodule
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
