columnSuffix: hjynlwwj
contentColumnType: text
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: ogTitle
instructions: "Titel für URL der beim Teilen bei z.B. Facebook, Twitter oder WhatsApp angezeigt wird.\r\n"
name: 'Open Graph Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
