columnSuffix: gvpyjxzk
contentColumnType: text
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: openingHours
instructions: null
name: Öffnungszeiten
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: null
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
