columnSuffix: null
contentColumnType: string
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: priceList
instructions: null
name: Preisliste
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
    - pdf
  branchLimit: null
  defaultUploadLocationSource: 'volume:5d513d88-6ffc-4ad6-8ee2-c8ae0137f535' # Dokumente
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:5b7d7792-f622-4289-a94e-f10fbe2ab5a9' # Bilder
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:5d513d88-6ffc-4ad6-8ee2-c8ae0137f535' # Dokumente
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
