columnSuffix: krkyoijj
contentColumnType: text
fieldGroup: da1d4526-3f54-4890-bcae-4d569b18dc7a # Common
handle: subsiteText
instructions: null
name: 'Subsite Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: e63ecf25-207b-44e7-a7fa-f741c17b8917 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
