dateModified: 1711307982
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      heading: Einzeleinträge
      type: heading
    -
      key: 'single:d2475e23-fe25-40e5-8e07-46ca1807882d' # Home
      type: native
    -
      key: 'single:9e388fcf-7cd8-4076-af22-13a6e7dedbe7'
      type: native
    -
      heading: Strukturen
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:669e2a7a-0c8c-4f09-ae3a-81ef311f8b72' # Unterseiten
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
email:
  fromEmail: digital@hi-schweiz.ch
  fromName: 'HI Base'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  documents:
    hasUrls: true
    name: Dokumente
    settings:
      path: media/documents
    type: craft\fs\Local
    url: '@primarySiteURL/media/documents'
  images:
    hasUrls: true
    name: Bilder
    settings:
      path: media/images
    type: craft\fs\Local
    url: '@primarySiteURL/media/images'
  videos:
    hasUrls: true
    name: Videos
    settings:
      path: media/videos
    type: craft\fs\Local
    url: '@primarySiteURL/media/videos'
meta:
  __names__:
    0be81558-7927-4e8f-866b-b3a571e4e8c2: 'Sekundäre Navigation' # Sekundäre Navigation
    4fe0479e-71f8-48ef-ab81-948b2edc8b8f: Standard # Standard
    5b7d7792-f622-4289-a94e-f10fbe2ab5a9: Bilder # Bilder
    5d513d88-6ffc-4ad6-8ee2-c8ae0137f535: Dokumente # Dokumente
    5f7e251b-0d47-4b0e-a1fd-37384588c244: 'Standort Text' # Standort Text
    9bb9b75a-9397-440a-8079-b62c7c281585: Bild # Bild
    11c2ce43-5a86-4949-9221-5c782ce91b2e: Alpwirtschaften # Alpwirtschaften
    12a480cf-2b03-4fbf-b964-740fd75d76de: Gallerie # Gallerie
    20c18c2a-6550-4e8f-aeac-27ee0bd5b80f: Starttext # Starttext
    96f07d02-866d-40f3-8796-19cbbcd7f5a1: Videos # Videos
    206b0441-3b56-4d0e-9491-0b8d30b4baed: SEO # SEO
    225ee2f5-06df-4c35-9611-df9d463ebc6d: 'HI Base' # HI Base
    669e2a7a-0c8c-4f09-ae3a-81ef311f8b72: Unterseiten # Unterseiten
    03689d2e-62bd-4a61-9f93-e75006143ccb: Autoren # Autoren
    53663f9e-7fed-498d-a311-d78a14218842: 'Standort Bild' # Standort Bild
    056651d5-c4a8-4d21-82ed-7a7eb78d225d: Location # Location
    8944216b-26d3-4667-be63-b2ba52e00229: Startbild # Startbild
    a0628d93-ae48-4103-bf03-dbcf0c4b84f3: 'Primäre Navigation' # Primäre Navigation
    a78c039f-e0dc-463b-9947-59494494f58d: 'Speisen Bilder' # Speisen Bilder
    a1543310-f6b3-4834-bb69-3a3b0ad7980d: Wirtschaft # Wirtschaft
    bc5f16e7-a4c2-48c2-891d-eb87b0f40cba: 'Authoren (intern)' # Authoren (intern)
    c0247ba7-b32e-4a5b-b2f9-ecab5f0e69dd: '@siteName' # @siteName
    c7cc6dde-192f-40ab-a654-a3004eaadd1b: 'Banner Text' # Banner Text
    cee0e87d-c85f-4ea7-b15e-80a6d13d3a76: 'Standort Titel' # Standort Titel
    d2eaac86-1ec9-4495-8b0d-2b96f0238762: Default # Default
    d7efc0ac-71c6-4ab3-b996-ad86a437d1d9: Alpwirtschaftsname # Alpwirtschaftsname
    d8b71489-beed-4561-af1e-7e4393a02db4: 'Gallerie Bilder' # Gallerie Bilder
    d61dde60-b864-45bf-b3b7-8aa89f1db4cd: Accordion # Accordion
    d309d3ff-d436-4d54-b34e-49191bcdadbf: 'Globale Inhalte' # Globale Inhalte
    d2475e23-fe25-40e5-8e07-46ca1807882d: Home # Home
    da1d4526-3f54-4890-bcae-4d569b18dc7a: Common # Common
    e9a2f0ef-4c4a-46a1-b506-ff66f2776221: 'Speisen Titel' # Speisen Titel
    e63ecf25-207b-44e7-a7fa-f741c17b8917: Simple # Simple
    ec1627dc-b5f5-48b7-9930-176066964085: Link # Link
    f0cef014-d080-4151-acce-bfaa4cd52d8c: Home # Home
    f8e4550b-6663-4892-b331-1059594b1a85: 'Titel Alpwirtschaften' # Titel Alpwirtschaften
    f71add43-bcd6-4ed0-ad64-7f1bd69b160b: 'Subsite Text' # Subsite Text
    f975f4a5-2e11-410c-bdb3-18a648976b12: Text # Text
    f22067e8-b7c8-4213-a1ca-4abe6d7e1f66: 'Standort Link' # Standort Link
    fdff2943-9d99-4e31-8950-f3bf9cbdfe69: 'Gallerie Titel' # Gallerie Titel
plugins:
  blur-hash:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.11
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: '@systemName'
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Europe/Zurich
