currLabel: 'Field Manager'
customIcon: null
enabled: true
handle: field-manager
icon: /Users/flouru/projects/hi-base-vite/backend/craft/vendor/verbb/field-manager/src/icon-mask.svg
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Field Manager'
prevLevel: 1
prevParent: null
prevUrl: field-manager
sortOrder: 5
subnavBehaviour: null
type: plugin
url: field-manager
