currLabel: Plug-in-Store
customIcon: null
enabled: true
handle: plugin-store
icon: plugin
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 1
newWindow: false
parent: null
prevLabel: Plug-in-Store
prevLevel: 1
prevParent: null
prevUrl: plugin-store
sortOrder: 17
subnavBehaviour: null
type: craft
url: plugin-store
