currLabel: Dateien
customIcon: null
enabled: true
handle: assets
icon: asset
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 1
newWindow: false
parent: null
prevLabel: Dateien
prevLevel: 1
prevParent: null
prevUrl: assets
sortOrder: 3
subnavBehaviour: null
type: craft
url: assets
