currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: '@appicons/graphql.svg'
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 11
subnavBehaviour: null
type: craft
url: graphql
