currLabel: Schemas
customIcon: null
enabled: true
handle: schemas
icon: null
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 2
newWindow: false
parent: cb419a92-0c31-4881-854e-2c9e4dad1779
prevLabel: Schemas
prevLevel: 2
prevParent: cb419a92-0c31-4881-854e-2c9e4dad1779
prevUrl: graphql/schemas
sortOrder: 12
subnavBehaviour: null
type: craft
url: graphql/schemas
