currLabel: SEO
customIcon: null
enabled: true
handle: seo
icon: /Users/flouru/projects/hi-base-vite/backend/craft/vendor/ether/seo/src/icon-mask.svg
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 1
newWindow: false
parent: null
prevLabel: SEO
prevLevel: 1
prevParent: null
prevUrl: seo
sortOrder: 6
subnavBehaviour: null
type: plugin
url: seo
