currLabel: Einstellungen
customIcon: null
enabled: true
handle: settings
icon: settings
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 1
newWindow: false
parent: null
prevLabel: Einstellungen
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 16
subnavBehaviour: null
type: craft
url: settings
