currLabel: Benutzer
customIcon: null
enabled: true
handle: users
icon: users
layout: d2eaac86-1ec9-4495-8b0d-2b96f0238762 # Default
level: 1
newWindow: false
parent: null
prevLabel: Benutzer
prevLevel: 1
prevParent: null
prevUrl: users
sortOrder: 4
subnavBehaviour: null
type: craft
url: users
