childBlocks: null
conditions: null
description: ''
enabled: true
field: 225e2c06-2164-4773-ba48-8967c3e93bbe # Inhaltsmodule
fieldLayouts:
  20d7425e-e5e2-4124-8c77-2e6e0c341fae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e8ad8253-23c4-4157-8274-03ec257dcfd3 # Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9c89d39-1eaf-4e7f-84e9-a8f560fb6d21
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: dfd997b9-1b35-4b38-a06c-6e4bec5bb1a3
        userCondition: null
group: null
groupChildBlockTypes: true
handle: accordion
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Accordion
sortOrder: 2
topLevel: true
