fieldLayouts:
  fb34f39c-dfd9-43dd-8f36-c71bcf3839e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f8fab2ab-9bf7-469d-9524-7f3e7bf76643
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f71add43-bcd6-4ed0-ad64-7f1bd69b160b # Subsite Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 636c773e-d1e7-47e0-8bd0-f0cab383ae56
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: f0527157-2e16-47a4-8c9f-50319f11da22
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6c54f856-fabe-4604-a951-0bd445a21af8 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10504ae5-4982-4576-be42-344d0eff45d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02e4577e-c0c7-4484-be04-13c5066ba715 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14ec004f-818d-45fc-996e-882c96171356
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 02cb27ed-13e8-4aec-9caa-d262aa471c42
            userCondition: null
          -
            elementCondition: null
            fieldUid: 0d758957-d062-436e-9180-2599a4d81f00 # Open Graph Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cf5e7f7-c1ea-4278-9a62-5f04d62bcfe7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f42ba710-ca52-47a7-ba20-0cf2c5349f00 # Open Graph Beschreibung
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b17081d-2a53-4242-944c-d32bdb1525a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2c3be5b-542e-43b1-bc37-7dc5c339cc71 # Open Graph Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 774c57ca-f22b-445d-b250-a817d1fcb041
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 6ebb075e-89b4-4f70-bed4-890939f84af8
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 669e2a7a-0c8c-4f09-ae3a-81ef311f8b72 # Unterseiten
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
