fieldLayouts:
  6ab1cd70-ca28-4450-9ff2-52ea99c163a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab02c4e5-a018-4b8a-98fc-20dbe11a51b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8944216b-26d3-4667-be63-b2ba52e00229 # Startbild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1fed71d-2a78-4cf7-a81f-b9eae3b6467a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 20c18c2a-6550-4e8f-aeac-27ee0bd5b80f # Starttext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2a033b5-cf88-466d-86d4-8f66d544ae9f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5be1203d-02eb-480f-a19e-2c5ada9e0318
            userCondition: null
          -
            elementCondition: null
            fieldUid: c7cc6dde-192f-40ab-a654-a3004eaadd1b # Banner Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 544dabdb-0486-4c44-b889-ace48e710368
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 4dd806c1-5888-4b4f-aa10-b699c1bb27e8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cee0e87d-c85f-4ea7-b15e-80a6d13d3a76 # Standort Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3cc2a46-ed4b-451d-b008-3ca68eb1a767
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f7e251b-0d47-4b0e-a1fd-37384588c244 # Standort Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c4919b5-21db-4174-8e11-039d57bd1145
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f22067e8-b7c8-4213-a1ca-4abe6d7e1f66 # Standort Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 872e854c-ab65-4c67-a828-1a0d5bf99ca2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53663f9e-7fed-498d-a311-d78a14218842 # Standort Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 045b5fd5-7321-47a1-94cb-d15dd652a03e
            userCondition: null
            warning: null
            width: 100
        name: Standort
        uid: 4ad65bc2-b05f-4b7e-aba6-ea9da085f49c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5c4e5480-3417-4c27-932d-b18c26bbea84 # Öffnungszeiten Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca6f4b74-c41d-4744-9325-d18519b40dad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54ff6f28-1b5a-4022-88cd-4452cdeae3d4 # Öffnungszeiten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c82eaa4d-3d17-463f-85b8-abbfe59f4e93
            userCondition: null
            warning: null
            width: 100
        name: Öffnungszeiten
        uid: 9d5aac34-fcde-47e1-b40e-590810a7c4bb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9a2f0ef-4c4a-46a1-b506-ff66f2776221 # Speisen Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e81291f8-b5d3-4074-86ff-49aa906bf63c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78c039f-e0dc-463b-9947-59494494f58d # Speisen Bilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68172b58-0d67-4a41-93fc-f63d46a412a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0ee3c248-c2a1-4623-aaf3-c37edee26838
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3d07c319-0c27-4ccb-8472-8930d0b62747 # Preisliste
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91f90c84-2030-4e05-b060-3aff8afc399a
            userCondition: null
            warning: null
            width: 100
        name: 'Speisen und Getränke'
        uid: 087422e4-e4c2-4417-8b12-75a92dfd312e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f8e4550b-6663-4892-b331-1059594b1a85 # Titel Alpwirtschaften
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4ebf1ab-4fd7-41c2-9950-7030c82d8b3e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11c2ce43-5a86-4949-9221-5c782ce91b2e # Alpwirtschaften
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b3be79f-5940-4e00-a6f0-25f4e75d6191
            userCondition: null
            warning: null
            width: 100
        name: Alpwirtschaften
        uid: ff31a43c-d24d-4dbb-9a27-99dc4187b522
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fdff2943-9d99-4e31-8950-f3bf9cbdfe69 # Galerie Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d90d5bd7-aaeb-4a94-91d5-063a1ed6beef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d8b71489-beed-4561-af1e-7e4393a02db4 # Galerie Bilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c616f0c5-1ce9-4dde-90f8-56abb200087a
            userCondition: null
            warning: null
            width: 100
        name: Gallerie
        uid: 68c86afe-abdb-443e-abe7-66c8806e76c3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 02e4577e-c0c7-4484-be04-13c5066ba715 # Meta Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc7f4c01-8a30-4b1c-b9c1-60216ef43cf0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c54f856-fabe-4604-a951-0bd445a21af8 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b76a3b4-ec98-4e9b-84cb-38efbcc59a5c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: deb4fd0f-276a-46b8-b142-8e086cd23764
            userCondition: null
          -
            elementCondition: null
            fieldUid: 0d758957-d062-436e-9180-2599a4d81f00 # Open Graph Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acafd7a1-2221-40d3-9421-dc1e3e6810de
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f42ba710-ca52-47a7-ba20-0cf2c5349f00 # Open Graph Beschreibung
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95db7b6d-493c-4fc4-8205-b570efb48ae8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2c3be5b-542e-43b1-bc37-7dc5c339cc71 # Open Graph Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0555c2d7-9c25-4315-ada3-710256dd1272
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 7f92f7a5-dfc9-4950-aa5c-92792ea66215
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: d2475e23-fe25-40e5-8e07-46ca1807882d # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
