fieldLayouts:
  6ab1cd70-ca28-4450-9ff2-52ea99c163a8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab02c4e5-a018-4b8a-98fc-20dbe11a51b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8944216b-26d3-4667-be63-b2ba52e00229 # Startbild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1fed71d-2a78-4cf7-a81f-b9eae3b6467a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 20c18c2a-6550-4e8f-aeac-27ee0bd5b80f # Starttext
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2a033b5-cf88-466d-86d4-8f66d544ae9f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 5be1203d-02eb-480f-a19e-2c5ada9e0318
            userCondition: null
          -
            elementCondition: null
            fieldUid: c7cc6dde-192f-40ab-a654-a3004eaadd1b # Banner Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 544dabdb-0486-4c44-b889-ace48e710368
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 4dd806c1-5888-4b4f-aa10-b699c1bb27e8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cee0e87d-c85f-4ea7-b15e-80a6d13d3a76 # Standort Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3cc2a46-ed4b-451d-b008-3ca68eb1a767
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f7e251b-0d47-4b0e-a1fd-37384588c244 # Standort Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c4919b5-21db-4174-8e11-039d57bd1145
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f22067e8-b7c8-4213-a1ca-4abe6d7e1f66 # Standort Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 872e854c-ab65-4c67-a828-1a0d5bf99ca2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53663f9e-7fed-498d-a311-d78a14218842 # Standort Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 045b5fd5-7321-47a1-94cb-d15dd652a03e
            userCondition: null
            warning: null
            width: 100
        name: Standort
        uid: 4ad65bc2-b05f-4b7e-aba6-ea9da085f49c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9a2f0ef-4c4a-46a1-b506-ff66f2776221 # Speisen Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e81291f8-b5d3-4074-86ff-49aa906bf63c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a78c039f-e0dc-463b-9947-59494494f58d # Speisen Bilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68172b58-0d67-4a41-93fc-f63d46a412a7
            userCondition: null
            warning: null
            width: 100
        name: 'Speisen und Getränke'
        uid: 087422e4-e4c2-4417-8b12-75a92dfd312e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 206b0441-3b56-4d0e-9491-0b8d30b4baed # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48d6174a-2eb0-45cf-8b9f-4d2c9f93d8ba
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 7f92f7a5-dfc9-4950-aa5c-92792ea66215
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: d2475e23-fe25-40e5-8e07-46ca1807882d # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
